---
name: 'PR Tests'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get install shellcheck
      - name: Run ShellCheck
        run: shellcheck -x tasks/*.sh files/*.sh

  test-install-task-on-ubuntu:
    strategy:
      matrix:
        os-details:
          - os: ubuntu-22.04
            codename: jammy
    #      - os: ubuntu-24.04
    #        codename: noble
    # Perforce hasn't yet released bolt on 24.04.
    runs-on: ${{ matrix.os-details.os }}
    needs: shellcheck
    steps:
      - uses: actions/checkout@v4
      - id: install-bolt
        uses: ./.github/actions/bolt
        with:
          os-codename: ${{ matrix.os-details.codename }}
      - name: Run openvox-agent install task
        run: bolt task run openvox_bootstrap::install --targets localhost --run-as root
      - name: Verify openvox-agent is installed
        run: |-
          [[ "$(/opt/puppetlabs/bin/puppet --version)" =~ [0-9]+\.[0-9]+\.[0-9]+ ]]

  test-install-task-on-other-os-via-containers:
    strategy:
      matrix:
        image:
          - almalinux:8
          - almalinux:9
          - rockylinux:8
          - rockylinux:9
          - debian:10
          - debian:11
          - debian:12
          - fedora:42
          - ubuntu:24.04
          # Need to pull in the repo GPG keys for sles
          #          - registry.suse.com/suse/sle15:15.6
    needs: shellcheck
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: openvox_bootstrap
      - id: prep
        uses: ./openvox_bootstrap/.github/actions/container_task_prep
      - name: Run openvox-agent install task manually
        env:
          PT__installdir: ${{ github.workspace }}
          PT_collection: openvox8
          PT_apt_source: "https://apt.overlookinfratech.com"
          PT_yum_source: "https://yum.overlookinfratech.com"
        run: ./openvox_bootstrap/tasks/install_linux.sh
      - name: Verify openvox-agent is installed
        run: /opt/puppetlabs/bin/puppet --version | grep -E '8\.[0-9]+'

  test-install-version:
    strategy:
      matrix:
        image:
          - rockylinux:9
          - fedora:41
          - debian:12
          - ubuntu:24.04
          # Need to pull in the repo GPG keys for sles
          #          - registry.suse.com/suse/sle15:15.6
    needs: shellcheck
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: openvox_bootstrap
      - id: prep
        uses: ./openvox_bootstrap/.github/actions/container_task_prep
      - name: Run openvox-agent install task manually
        env:
          PT__installdir: ${{ github.workspace }}
          PT_version: "8.14.0"
          PT_apt_source: "https://apt.overlookinfratech.com"
          PT_yum_source: "https://yum.overlookinfratech.com"
        run: ./openvox_bootstrap/tasks/install_linux.sh
      - name: Verify openvox-agent is installed
        run: /opt/puppetlabs/bin/puppet --version | grep '8.14.0'
