---
name: 'PR Tests'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ShellCheck
        run: sudo apt-get install shellcheck
      - name: Run ShellCheck
        run: shellcheck tasks/*.sh

  test-install-task-on-ubuntu:
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
      - uses: actions/checkout@v4
      #      - name: Install dependencies
      #        run: sudo apt wget
      - name: Install Bolt
        run: |-
          wget https://apt.puppet.com/puppet-tools-release-noble.deb
          sudo dpkg -i puppet-tools-release-noble.deb
          sudo apt update
          sudo apt install -y puppet-bolt
      - name: Install module dependencies
        run: bolt module install
      - name: Run openvox-agent install task
        run: bolt task run openvox_bootstrap::install --targets localhost
      - name: Verify openvox-agent is installed
        run: puppet --version
