---
name: 'PR Tests'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ShellCheck
        run: sudo apt-get install shellcheck
      - name: Run ShellCheck
        run: shellcheck tasks/*.sh

  test-install-task-on-ubuntu:
    # Perforce hasn't yet released bolt on 24.04.
    runs-on: ubuntu-22.04
    needs: shellcheck
    steps:
      - uses: actions/checkout@v4
      - name: Install Bolt
        run: |-
          wget https://apt.puppet.com/puppet-tools-release-jammy.deb
          sudo dpkg -i puppet-tools-release-jammy.deb
          sudo apt update
          sudo apt install -y puppet-bolt
      - name: Install module dependencies
        run: bolt module install
      - name: Run openvox-agent install task
        run: bolt task run openvox_bootstrap::install --targets localhost --run-as root
      - name: Verify openvox-agent is installed
        run: |-
          [[ "$(/opt/puppetlabs/bin/puppet --version)" =~ [0-9]+\.[0-9]+\.[0-9]+ ]]
